AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdaAMIBackups:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Create AMI for backup
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::379673441375:role/lamda-ec2-ami-role'
      Runtime: python2.7
      Timeout: 60
